### PR TITLE
chore(Dockerfile) Update container to slim

### PR DESCRIPTION
**Pull request by bkochendorfer**
## Goal

The slim container has less known CVEs. Pinning the SHA will allow
Dependabot to make updates when updates are made to the underlying
container instead of waiting on other build requirements.

### CODE REVIEW

**Review by kschelonka — APPROVED** [review]

**Review by bassrock — DISMISSED** [review]

**Comment by bkochendorfer** [comment]
Why is the linter still failing?

**Comment by jpetto** [comment]
> Why is the linter still failing?

uh, very good question. i'll look into this later today. (github linter has been my enemy this week.)

**Review by bassrock — APPROVED** [review]

**Comment by bkochendorfer** [comment]
What is circleci doing now :sob:

**Comment by jpetto** [comment]
i have a hunch this is because you are PR'ing from a fork. can you submit the PR as a new branch on this repo? (this was a change for me coming over from mozilla 🙃 )

**Review by duallain — APPROVED** [review]

**Pull request closed without merging**
